version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "ZshanUmar"
github_repo = "my-sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-8qqndMmExmbR"
cloudformation_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-S1lmMRk9iDcB"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-4cv0trari41v"
image_repository = ""
region = "ap-southeast-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-nbStoqUcYLjd"
cloudformation_execution_role = "arn:aws:iam::077736414234:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-gBghCBR2DguB"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-lercfxtcgrhj"
image_repository = ""
region = "ap-southeast-1"
